# **Welcome to numpy**


In [2]:
import numpy as np #importing...

In [3]:
arr= np.array([1,2,3,4,5],np.int64) #assignment

In [4]:
print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5], dtype=int64)

In [5]:
print(arr.dtype)

int64


In [6]:
print(arr.shape) #gives the shape of array

(5,)


## ***Conversion from lists and tuples***


In [7]:
l=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
print(l)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
l.shape

(3, 3)

In [10]:
l.size

9

## ***Intrinsic array creation objects***

In [11]:
#for a array of specified zeros
zer=np.zeros((5,5)) #specifies 5X5 matrix with all zeroes

In [12]:
zer

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
arr2= np.arange(1,10,2) #same as range in normal python

In [14]:
arr2

array([1, 3, 5, 7, 9])

In [15]:
# for equal division of a range into some number of elements
lsp=np.linspace(1,10,34) #means from 1 to 10 i need 34 elements with same difference between them

In [16]:
lsp


array([ 1.        ,  1.27272727,  1.54545455,  1.81818182,  2.09090909,
        2.36363636,  2.63636364,  2.90909091,  3.18181818,  3.45454545,
        3.72727273,  4.        ,  4.27272727,  4.54545455,  4.81818182,
        5.09090909,  5.36363636,  5.63636364,  5.90909091,  6.18181818,
        6.45454545,  6.72727273,  7.        ,  7.27272727,  7.54545455,
        7.81818182,  8.09090909,  8.36363636,  8.63636364,  8.90909091,
        9.18181818,  9.45454545,  9.72727273, 10.        ])

In [17]:
'''we can create an identity matrix of any size'''
# <var name>=np.identity(<specify size here>)
#note: these are all float numbers
idn=np.identity(7)

In [18]:
idn


array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [19]:
'''reshape'''
arr9=np.arange(99)

In [20]:
arr9


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

### these doesn't change original array until you assign them to actual variable

In [21]:
arr9=arr9.reshape(3,33)
#you cannot re shape it other than correct divisions

In [22]:
arr9

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

### to chage it into normal you can simple use <>.ravel() function

In [23]:
arr9=arr9.ravel()  #changes into 1D array

In [24]:
arr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

## Working with axis

In [25]:
ar=np.array([[1,2,3],[4,5,6],[7,1,0]])

In [26]:
ar #---------->
#  | a x i s 1 (horizontal)
#  | x
#  | i 
#  | s 
#  V 0 (vertical)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [27]:
ar.sum(axis=0)


array([12,  8,  9])

In [28]:
ar.sum(axis=1)

array([ 6, 15,  8])

## For a transpose of a matrix simple use <>.T


In [29]:
ar.T


array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

## To get all the elements in the matrix use <>.flat (this gives a iterator to traverse so use list or tuple before it)

In [30]:
l= list(ar.flat)
print(l)

[1, 2, 3, 4, 5, 6, 7, 1, 0]


## to know the dimension <>.ndim

In [31]:
ar.ndim

2

In [32]:
ar.nbytes #this gives total bytes consumed by the elements in your matrix

36

In [33]:
ar.argmax() #gives index of maximum element

6

In [34]:
ar.argmin() #gives index of minimum element

8

In [35]:
ar.argsort() #gives the indexes only, not elements. traceback indexes to know elements

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [36]:
ar.argmax(axis=1) #gives index of maximum element

array([2, 2, 0], dtype=int64)

In [37]:
ar.argmin(axis=0) #gives index of minimum element

array([0, 2, 2], dtype=int64)

In [38]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [39]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [40]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [41]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [42]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [43]:
ar2=np.array([[1, 5, 3],
       [9, 2, 7],
       [8, 1, 0]])

# Sum of two matrices

In [44]:
ar+ar2

array([[ 2,  7,  6],
       [13,  7, 13],
       [15,  2,  0]])

# Product of two matrices


In [45]:
ar*ar2

array([[ 1, 10,  9],
       [36, 10, 42],
       [56,  1,  0]])

In [46]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [47]:
sqar=np.array([[1,4,9],[25,36,49],[64,81,100]])

In [48]:
np.sqrt(sqar)

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [49]:
sqar.sum()

369

In [50]:
sqar.max()


100

In [51]:
sqar.min()


1

In [52]:
sqar

array([[  1,   4,   9],
       [ 25,  36,  49],
       [ 64,  81, 100]])

In [53]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [54]:
np.count_nonzero(ar)

8

In [55]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
import sys


In [58]:
l_py=[0,4,55,2]

In [59]:
l_np=np.array(l_py)

In [60]:
sys.getsizeof(1)*len(l_py)

112

In [61]:
l_np.itemsize*l_np.size

16

# PYTHON ENGINEER

In [62]:
import numpy as np

In [63]:
l=[1,2,3,4,5]
a=np.array(l)

In [64]:
a

array([1, 2, 3, 4, 5])

In [65]:
a=np.append(a,7)

In [66]:
a

array([1, 2, 3, 4, 5, 7])

### Inverse of a matrix  which means that inv * actual = identity matrix

In [67]:
ary=np.array([[1,2],[3,4]])

In [68]:
ary

array([[1, 2],
       [3, 4]])

### NOTE: Matrix having determinant (det) =0 has no inverse. If you try to find its inverse then you will get an error

In [69]:
np.linalg.inv(ary)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [70]:
np.linalg.det(ary)

-2.0000000000000004

In [71]:
ary.T

array([[1, 3],
       [2, 4]])

In [72]:
ary=np.array([[1,2,3],[4,5,6],[3,4,1]])
print(ary)
print(np.linalg.inv(ary))
print(np.linalg.det(ary))
print(ary.T)

[[1 2 3]
 [4 5 6]
 [3 4 1]]
[[-1.58333333  0.83333333 -0.25      ]
 [ 1.16666667 -0.66666667  0.5       ]
 [ 0.08333333  0.16666667 -0.25      ]]
11.999999999999995
[[1 4 3]
 [2 5 4]
 [3 6 1]]


### To get the diagonal elements

In [73]:
np.diag(ary)

array([1, 5, 1])

In [74]:
sum(np.diag(ary))


7

# SLICING/INDEXING

In [75]:
ary

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 1]])

In [76]:
ary[0,1:3]   #in 0th row elements from index 1 to 3(3excluded)

array([2, 3])

In [77]:
ary[2,0:1]  #coordinates are [x,y] the values in x and y are held by slicing

array([3])

In [78]:
ary[-1,-1] #last element i,e.., last row last element

1

# bool indexing

**traditionally used for an condition checking**

In [79]:
ar=np.array([[1,2],[3,4],[5,6]])
print(ar)

[[1 2]
 [3 4]
 [5 6]]


In [80]:
bool_idx= ar >2

In [81]:
print(bool_idx)
print(ar[bool_idx]) 
#returns the array of elements satisfying the given condition


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [82]:
print(ar[ar>2]) #this also does the same more efficient

[3 4 5 6]


## Fancy Indexing

In [83]:
#let
ar=np.array([10,32,45,645,674,34,46,23,886,34])
b=[1,4,6]
print(ar[b]) #elements of b are treated as indexes

[ 32 674  46]


In [84]:
print(ar[ar%2==0])

[ 10  32 674  34  46 886  34]


# Reshaping


In [85]:
 ar=np.arange(1,7)

In [86]:
ar

array([1, 2, 3, 4, 5, 6])

In [87]:
a.shape

(6,)

In [88]:
b=a.reshape(2,3) #throws an error if shape cant be applied

In [89]:
b

array([[1, 2, 3],
       [4, 5, 7]])

In [90]:
b=a.reshape(6,1)
print(b)
b=a[:,np.newaxis]
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [7]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [7]]


In [91]:
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [7]]
(6, 1)


# CONCATENATION


In [92]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
#hstack() (horizonal concatenation)
#Vstack() (Vertical concatenation)
c=np.hstack((a,b))
print(c)
c=np.vstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


# Broadcasting

In [93]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
a=np.array([1,0,1]) 
#shoul match number of elements in a row. 
#column need not to be specified to n times
x=x+a
print(x)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [12 12 14]]


# Functions and Axis

In [94]:
a=np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
print(a)
print(a.sum(axis=1))
print(a.sum(axis=0))
print(a.mean(axis=0))
print(a.mean())
print(a.var())
print(f'{a.std():.2f}')

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]
[ 70 140]
[24 26 28 30 32 34 36]
[12. 13. 14. 15. 16. 17. 18.]
15.0
29.0
5.39


# DATATYPES

In [95]:
x=np.array([1.0,2.0,3.0], dtype=np.float16) 
#this declaration is to save space float32 and float64 are recommended
print(x)
print(x.dtype)

[1. 2. 3.]
float16


# Copying

In [96]:
a=np.array([1,2,3])
b=a.copy()
# if you dont use copy then operations/changes did to b will also apply on a

# Array Generation


In [97]:
a=np.zeros((2,3)) #zeroes all over the array
print(a)
a=np.ones((2,3)) #ones all over the array
print(a)
a=np.full((2,3),17.0)  #specified value will be all over the array
print(a)
a=np.eye(3) #gives an identity matrix
print(a)
a=np.arange(20) #gives all the elements linear fashion
print(a)
a=np.linspace(1,20,4) #linspace(<start>,<stop>,<how many elements needed>)
print(a)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[17. 17. 17.]
 [17. 17. 17.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.          7.33333333 13.66666667 20.        ]


# Random Numbers

In [98]:
a=np.random.random((3,2)) #will always be in range 0-1
print(a)
a=np.random.rand(3,2) #normal/Gaussian distribution
print(a)
a=np.random.rand(1000)
print(a.mean(),a.var())

a=np.random.randint(10,size=(3,3))
# the lower and upperbounds should be specified 
# if no lower bound 0 is considered as lower bound
print(a)


'''even the above and below lines do the same operation choice is preffered 
in a known boundary of elements i.e., to choose from a particular numbers'''
a=np.random.choice([5,6,4,7,8],size=(3,3)) #choic(<num/list>,size=<num/dimension_of_matrix>)
print(a)


[[0.93417134 0.95453264]
 [0.2432496  0.07196345]
 [0.79985063 0.32634981]]
[[0.95748607 0.19566289]
 [0.02861054 0.67212369]
 [0.05904969 0.90241525]]
0.517920995220861 0.0824951692466951
[[7 4 6]
 [3 1 7]
 [1 6 0]]
[[5 6 6]
 [7 4 5]
 [7 8 4]]


# Linear algebra

In [99]:
a=np.array([[1,2],[3,4]])
eigenvalues,eigenvectors=np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## To compare two arrays always use np.allclose(arr1,arr2)

In [100]:
import numpy as np

In [101]:
l=[[0,0,0,0,0],
    [0,0,0,0,1],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0]
   ]

In [102]:
l=np.array(l)

In [103]:
l

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [104]:
x=np.argwhere(l==1)
print(x)
print(abs(x[0][1]-3)+ abs(x[0][0]-3))

[[1 4]]
3
